"""Created model for job_applications table.

Revision ID: 15501dcbd8e2
Revises: 9f4bb81c8202
Create Date: 2022-08-30 14:09:30.864500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15501dcbd8e2'
down_revision = '9f4bb81c8202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('job_position_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant_details.id'], ),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applications')
    # ### end Alembic commands ###
