"""Added user image column to user model

Revision ID: 9281c808751b
Revises: 15501dcbd8e2
Create Date: 2022-10-28 10:45:37.927955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9281c808751b'
down_revision = '15501dcbd8e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_img')
    # ### end Alembic commands ###
