"""changed foreign key in employment log from employee to job_position

Revision ID: 9f4bb81c8202
Revises: d89ef348488d
Create Date: 2022-08-07 12:48:52.413446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4bb81c8202'
down_revision = 'd89ef348488d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment_logs', sa.Column('job_position_id', sa.Integer(), nullable=True))
    op.drop_constraint('employment_logs_employer_id_fkey', 'employment_logs', type_='foreignkey')
    op.create_foreign_key(None, 'employment_logs', 'job_positions', ['job_position_id'], ['id'])
    op.drop_column('employment_logs', 'employer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment_logs', sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employment_logs', type_='foreignkey')
    op.create_foreign_key('employment_logs_employer_id_fkey', 'employment_logs', 'employer_details', ['employer_id'], ['id'])
    op.drop_column('employment_logs', 'job_position_id')
    # ### end Alembic commands ###
